In [1]:
from os import error
import numpy as np
import pandas as pd
from numpy.core.fromnumeric import shape
from sklearn.metrics import silhouette_score
from sklearn.metrics import davies_bouldin_score
from sklearn.metrics import calinski_harabasz_score
from SOM.SelfOrganisingMaps import SelfOrganisingMaps
from WOA.WhaleClustersOptimization import WhaleClustersOptimization
from Models.Core.ObjGlobalRequest import ObjGlobalRequest
import Models.ObjHotelReviews as ObjHotelReviews
import Repository.HotelReviewsRepository as HotelReviewsRepository
import Repository.UsersRepository as UsersRepository
import Helper.ListHelper as ListHelper
Users = UsersRepository.GetList(ObjGlobalRequest())
User = ObjHotelReviews.ObjHotelReviews_GetList_Request()
User.User_ID = Users.List[0]["User_ID"]
ReviewsRequest0 = ObjGlobalRequest(User)
ReviewsResponse0 = HotelReviewsRepository.GetList(ReviewsRequest0)
Matrix = []
MatrixSize = len(ReviewsResponse0.List)
BatchSize = 1000
Clusters = 3
SOM = SelfOrganisingMaps(Clusters, MatrixSize, 50)
_silhouette_score = 0
_bouldin_score = 0
_calinski_harabasz_score = 0
BatchNumber = 0
index = 0
indexData = 0

for u in Users.List:
    if(index == 0):
        Matrix = np.zeros((BatchSize, MatrixSize), dtype=int)
    User = ObjHotelReviews.ObjHotelReviews_GetList_Request()
    User.User_ID = u["User_ID"]
    ReviewsRequest = ObjGlobalRequest(User)
    ReviewsResponse = HotelReviewsRepository.GetList(ReviewsRequest)
    UsersReviews_DataFrame = pd.DataFrame(ReviewsResponse.List)
    Matrix[index] = UsersReviews_DataFrame["Rate"]
    print(f"indexData: {indexData}, User_ID: {u['User_ID']}" , end="\r")
    index += 1
    indexData += 1
    if (index + 1 == BatchSize):
        BatchNumber += 1
        print("\n Batch Number: ", BatchNumber)
        SOM.Fit(Matrix)
        # print("shape Matrix: ", shape(Matrix))
        # Optimization Cluster Centers  
        print(shape(SOM.Weights))
        woa = WhaleClustersOptimization(SOM.Weights, SOM.Labels, Matrix)
        # print(shape(woa.basePoint))        
        # print(shape(woa._sols))
        for _ in range(10):
            woa.optimize()
        # print(shape(woa._best_solution))
        # print(woa._best_solution)
        SOM.Weights = woa._best_solution
        Unique_Labels = ListHelper.Unique(SOM.Labels)
        if (len(Unique_Labels) == 1):
            if(SOM.Labels[0] == 0):
                SOM.Labels[0] = 1
            else:
                SOM.Labels[0] = 0
        _silhouette_score += silhouette_score(Matrix, SOM.Labels, metric="euclidean")
        _bouldin_score += davies_bouldin_score(Matrix, SOM.Labels)
        _calinski_harabasz_score += calinski_harabasz_score(Matrix, SOM.Labels)
        index = 0

print("For n_clusters =", Clusters, "The silhouette_score is :", _silhouette_score)
print("For n_clusters =", Clusters, "The bouldin_score is :", _bouldin_score, "lower Is better")
print("For n_clusters =", Clusters, "The calinski_harabasz_score is :", _calinski_harabasz_score, "higher Is better")

print("End Of SOM Clustering")
# For n_clusters = 3 The silhouette_score is : 0
# For n_clusters = 3 The bouldin_score is : 0 lower Is better
# For n_clusters = 3 The calinski_harabasz_score is : 0 higher Is better



init random weights ... [[1.48021007 3.42439831 3.2023938  ... 3.92262581 4.95795892 1.79544792]
 [4.10854018 1.23826414 0.33423789 ... 2.28850696 2.21194532 1.54650692]
 [3.88486243 4.35205943 4.17426035 ... 1.71119902 2.65394701 0.11162552]]
indexData: 998, User_ID: 344837
 Batch Number:  1
(3, 12773)
_sols :  (10, 3, 12773)
_best_solutions :  (1, 2)
_sols :  (10, 3, 12773)
_best_solutions :  (2, 2)
_sols :  (10, 3, 12773)
_best_solutions :  (3, 2)
_sols :  (10, 3, 12773)
_best_solutions :  (4, 2)
_sols :  (10, 3, 12773)
_best_solutions :  (5, 2)
_sols :  (10, 3, 12773)
_best_solutions :  (6, 2)
_sols :  (10, 3, 12773)
_best_solutions :  (7, 2)
_sols :  (10, 3, 12773)
_best_solutions :  (8, 2)
_sols :  (10, 3, 12773)
_best_solutions :  (9, 2)
_sols :  (10, 3, 12773)
_best_solutions :  (10, 2)
indexData: 1997, User_ID: 722609
 Batch Number:  2
(3, 12773)
_sols :  (10, 3, 12773)
_best_solutions :  (1, 2)
_sols :  (10, 3, 12773)
_best_solutions :  (2, 2)
_sols :  (10, 3, 12773)
_best_so

In [2]:
from os import error
import numpy as np
import pandas as pd
from numpy.core.fromnumeric import shape
from sklearn.metrics import silhouette_score
from sklearn.metrics import davies_bouldin_score
from sklearn.metrics import calinski_harabasz_score
from SOM.SelfOrganisingMaps import SelfOrganisingMaps
from WOA.WhaleClustersOptimization import WhaleClustersOptimization
from Models.Core.ObjGlobalRequest import ObjGlobalRequest
import Models.ObjHotelReviews as ObjHotelReviews
import Repository.HotelReviewsRepository as HotelReviewsRepository
import Repository.UsersRepository as UsersRepository
import Helper.ListHelper as ListHelper
Users = UsersRepository.GetList(ObjGlobalRequest())
User = ObjHotelReviews.ObjHotelReviews_GetList_Request()
User.User_ID = Users.List[0]["User_ID"]
ReviewsRequest0 = ObjGlobalRequest(User)
ReviewsResponse0 = HotelReviewsRepository.GetList(ReviewsRequest0)
Matrix = []
MatrixSize = len(ReviewsResponse0.List)
BatchSize = 1000
Clusters = 5
SOM = SelfOrganisingMaps(Clusters, MatrixSize, 50)
_silhouette_score = 0
_bouldin_score = 0
_calinski_harabasz_score = 0
BatchNumber = 0
index = 0
indexData = 0

for u in Users.List:
    if(index == 0):
        Matrix = np.zeros((BatchSize, MatrixSize), dtype=int)
    User = ObjHotelReviews.ObjHotelReviews_GetList_Request()
    User.User_ID = u["User_ID"]
    ReviewsRequest = ObjGlobalRequest(User)
    ReviewsResponse = HotelReviewsRepository.GetList(ReviewsRequest)
    UsersReviews_DataFrame = pd.DataFrame(ReviewsResponse.List)
    Matrix[index] = UsersReviews_DataFrame["Rate"]
    print(f"indexData: {indexData}, User_ID: {u['User_ID']}" , end="\r")
    index += 1
    indexData += 1
    if (index + 1 == BatchSize):
        BatchNumber += 1
        print("\n Batch Number: ", BatchNumber)
        SOM.Fit(Matrix)
        # print("shape Matrix: ", shape(Matrix))
        # Optimization Cluster Centers  
        print(shape(SOM.Weights))
        woa = WhaleClustersOptimization(SOM.Weights, SOM.Labels, Matrix)
        # print(shape(woa.basePoint))        
        # print(shape(woa._sols))
        for _ in range(10):
            woa.optimize()
        # print(shape(woa._best_solution))
        # print(woa._best_solution)
        SOM.Weights = woa._best_solution
        Unique_Labels = ListHelper.Unique(SOM.Labels)
        if (len(Unique_Labels) == 1):
            if(SOM.Labels[0] == 0):
                SOM.Labels[0] = 1
            else:
                SOM.Labels[0] = 0
        _silhouette_score += silhouette_score(Matrix, SOM.Labels, metric="euclidean")
        _bouldin_score += davies_bouldin_score(Matrix, SOM.Labels)
        _calinski_harabasz_score += calinski_harabasz_score(Matrix, SOM.Labels)
        index = 0

print("For n_clusters =", Clusters, "The silhouette_score is :", _silhouette_score)
print("For n_clusters =", Clusters, "The bouldin_score is :", _bouldin_score, "lower Is better")
print("For n_clusters =", Clusters, "The calinski_harabasz_score is :", _calinski_harabasz_score, "higher Is better")

print("End Of SOM Clustering")
# For n_clusters = 3 The silhouette_score is : 0
# For n_clusters = 3 The bouldin_score is : 0 lower Is better
# For n_clusters = 3 The calinski_harabasz_score is : 0 higher Is better



init random weights ... [[4.93191261 2.87779108 3.04490686 ... 2.77238136 0.0821909  0.77173978]
 [2.15011399 0.36969533 1.4524415  ... 1.74811145 1.24344037 4.54533244]
 [4.86710777 2.6755781  3.43941809 ... 1.5463069  0.34472312 0.88183629]
 [3.11942424 2.08438419 3.92360444 ... 1.54670272 2.07070496 4.96825156]
 [0.83184534 1.16233136 1.64013639 ... 2.98064367 2.599771   2.97549019]]
indexData: 998, User_ID: 375260
 Batch Number:  1
(5, 12773)
_sols :  (10, 5, 12773)
_best_solutions :  (1, 2)
_sols :  (10, 5, 12773)
_best_solutions :  (2, 2)
_sols :  (10, 5, 12773)
_best_solutions :  (3, 2)
_sols :  (10, 5, 12773)
_best_solutions :  (4, 2)
_sols :  (10, 5, 12773)
_best_solutions :  (5, 2)
_sols :  (10, 5, 12773)
_best_solutions :  (6, 2)
_sols :  (10, 5, 12773)
_best_solutions :  (7, 2)
_sols :  (10, 5, 12773)
_best_solutions :  (8, 2)
_sols :  (10, 5, 12773)
_best_solutions :  (9, 2)
_sols :  (10, 5, 12773)
_best_solutions :  (10, 2)
indexData: 1997, User_ID: 17796
 Batch Number:  

In [3]:
from os import error
import numpy as np
import pandas as pd
from numpy.core.fromnumeric import shape
from sklearn.metrics import silhouette_score
from sklearn.metrics import davies_bouldin_score
from sklearn.metrics import calinski_harabasz_score
from SOM.SelfOrganisingMaps import SelfOrganisingMaps
from WOA.WhaleClustersOptimization import WhaleClustersOptimization
from Models.Core.ObjGlobalRequest import ObjGlobalRequest
import Models.ObjHotelReviews as ObjHotelReviews
import Repository.HotelReviewsRepository as HotelReviewsRepository
import Repository.UsersRepository as UsersRepository
import Helper.ListHelper as ListHelper
Users = UsersRepository.GetList(ObjGlobalRequest())
User = ObjHotelReviews.ObjHotelReviews_GetList_Request()
User.User_ID = Users.List[0]["User_ID"]
ReviewsRequest0 = ObjGlobalRequest(User)
ReviewsResponse0 = HotelReviewsRepository.GetList(ReviewsRequest0)
Matrix = []
MatrixSize = len(ReviewsResponse0.List)
BatchSize = 1000
Clusters = 7
SOM = SelfOrganisingMaps(Clusters, MatrixSize, 50)
_silhouette_score = 0
_bouldin_score = 0
_calinski_harabasz_score = 0
BatchNumber = 0
index = 0
indexData = 0

for u in Users.List:
    if(index == 0):
        Matrix = np.zeros((BatchSize, MatrixSize), dtype=int)
    User = ObjHotelReviews.ObjHotelReviews_GetList_Request()
    User.User_ID = u["User_ID"]
    ReviewsRequest = ObjGlobalRequest(User)
    ReviewsResponse = HotelReviewsRepository.GetList(ReviewsRequest)
    UsersReviews_DataFrame = pd.DataFrame(ReviewsResponse.List)
    Matrix[index] = UsersReviews_DataFrame["Rate"]
    print(f"indexData: {indexData}, User_ID: {u['User_ID']}" , end="\r")
    index += 1
    indexData += 1
    if (index + 1 == BatchSize):
        BatchNumber += 1
        print("\n Batch Number: ", BatchNumber)
        SOM.Fit(Matrix)
        # print("shape Matrix: ", shape(Matrix))
        # Optimization Cluster Centers  
        print(shape(SOM.Weights))
        woa = WhaleClustersOptimization(SOM.Weights, SOM.Labels, Matrix)
        # print(shape(woa.basePoint))        
        # print(shape(woa._sols))
        for _ in range(10):
            woa.optimize()
        # print(shape(woa._best_solution))
        # print(woa._best_solution)
        SOM.Weights = woa._best_solution
        Unique_Labels = ListHelper.Unique(SOM.Labels)
        if (len(Unique_Labels) == 1):
            if(SOM.Labels[0] == 0):
                SOM.Labels[0] = 1
            else:
                SOM.Labels[0] = 0
        _silhouette_score += silhouette_score(Matrix, SOM.Labels, metric="euclidean")
        _bouldin_score += davies_bouldin_score(Matrix, SOM.Labels)
        _calinski_harabasz_score += calinski_harabasz_score(Matrix, SOM.Labels)
        index = 0

print("For n_clusters =", Clusters, "The silhouette_score is :", _silhouette_score)
print("For n_clusters =", Clusters, "The bouldin_score is :", _bouldin_score, "lower Is better")
print("For n_clusters =", Clusters, "The calinski_harabasz_score is :", _calinski_harabasz_score, "higher Is better")

print("End Of SOM Clustering")
# For n_clusters = 3 The silhouette_score is : 0
# For n_clusters = 3 The bouldin_score is : 0 lower Is better
# For n_clusters = 3 The calinski_harabasz_score is : 0 higher Is better



init random weights ... [[3.91468206 2.34790927 3.69739851 ... 3.03416378 3.51112805 4.97284304]
 [4.58554874 2.67359891 2.69541136 ... 4.39688611 1.974117   4.25871006]
 [4.45386693 3.67882302 4.03529676 ... 0.598685   0.79518153 3.52043653]
 ...
 [0.75617755 2.71901279 1.7993778  ... 0.66914164 4.71761697 4.75487576]
 [0.07049408 4.25952297 4.48811676 ... 0.99219728 1.47888916 0.39090559]
 [3.56422905 0.12663661 4.08715269 ... 1.49788312 3.54484703 0.31860227]]
indexData: 998, User_ID: 280971
 Batch Number:  1
(7, 12773)
_sols :  (10, 7, 12773)
_best_solutions :  (1, 2)
_sols :  (10, 7, 12773)
_best_solutions :  (2, 2)
_sols :  (10, 7, 12773)
_best_solutions :  (3, 2)
_sols :  (10, 7, 12773)
_best_solutions :  (4, 2)
_sols :  (10, 7, 12773)
_best_solutions :  (5, 2)
_sols :  (10, 7, 12773)
_best_solutions :  (6, 2)
_sols :  (10, 7, 12773)
_best_solutions :  (7, 2)
_sols :  (10, 7, 12773)
_best_solutions :  (8, 2)
_sols :  (10, 7, 12773)
_best_solutions :  (9, 2)
_sols :  (10, 7, 1277

In [4]:
from os import error
import numpy as np
import pandas as pd
from numpy.core.fromnumeric import shape
from sklearn.metrics import silhouette_score
from sklearn.metrics import davies_bouldin_score
from sklearn.metrics import calinski_harabasz_score
from SOM.SelfOrganisingMaps import SelfOrganisingMaps
from WOA.WhaleClustersOptimization import WhaleClustersOptimization
from Models.Core.ObjGlobalRequest import ObjGlobalRequest
import Models.ObjHotelReviews as ObjHotelReviews
import Repository.HotelReviewsRepository as HotelReviewsRepository
import Repository.UsersRepository as UsersRepository
import Helper.ListHelper as ListHelper
Users = UsersRepository.GetList(ObjGlobalRequest())
User = ObjHotelReviews.ObjHotelReviews_GetList_Request()
User.User_ID = Users.List[0]["User_ID"]
ReviewsRequest0 = ObjGlobalRequest(User)
ReviewsResponse0 = HotelReviewsRepository.GetList(ReviewsRequest0)
Matrix = []
MatrixSize = len(ReviewsResponse0.List)
BatchSize = 1000
Clusters = 9
SOM = SelfOrganisingMaps(Clusters, MatrixSize, 50)
_silhouette_score = 0
_bouldin_score = 0
_calinski_harabasz_score = 0
BatchNumber = 0
index = 0
indexData = 0

for u in Users.List:
    if(index == 0):
        Matrix = np.zeros((BatchSize, MatrixSize), dtype=int)
    User = ObjHotelReviews.ObjHotelReviews_GetList_Request()
    User.User_ID = u["User_ID"]
    ReviewsRequest = ObjGlobalRequest(User)
    ReviewsResponse = HotelReviewsRepository.GetList(ReviewsRequest)
    UsersReviews_DataFrame = pd.DataFrame(ReviewsResponse.List)
    Matrix[index] = UsersReviews_DataFrame["Rate"]
    print(f"indexData: {indexData}, User_ID: {u['User_ID']}" , end="\r")
    index += 1
    indexData += 1
    if (index + 1 == BatchSize):
        BatchNumber += 1
        print("\n Batch Number: ", BatchNumber)
        SOM.Fit(Matrix)
        # print("shape Matrix: ", shape(Matrix))
        # Optimization Cluster Centers  
        print(shape(SOM.Weights))
        woa = WhaleClustersOptimization(SOM.Weights, SOM.Labels, Matrix)
        # print(shape(woa.basePoint))        
        # print(shape(woa._sols))
        for _ in range(10):
            woa.optimize()
        # print(shape(woa._best_solution))
        # print(woa._best_solution)
        SOM.Weights = woa._best_solution
        Unique_Labels = ListHelper.Unique(SOM.Labels)
        if (len(Unique_Labels) == 1):
            if(SOM.Labels[0] == 0):
                SOM.Labels[0] = 1
            else:
                SOM.Labels[0] = 0
        _silhouette_score += silhouette_score(Matrix, SOM.Labels, metric="euclidean")
        _bouldin_score += davies_bouldin_score(Matrix, SOM.Labels)
        _calinski_harabasz_score += calinski_harabasz_score(Matrix, SOM.Labels)
        index = 0

print("For n_clusters =", Clusters, "The silhouette_score is :", _silhouette_score)
print("For n_clusters =", Clusters, "The bouldin_score is :", _bouldin_score, "lower Is better")
print("For n_clusters =", Clusters, "The calinski_harabasz_score is :", _calinski_harabasz_score, "higher Is better")

print("End Of SOM Clustering")
# For n_clusters = 3 The silhouette_score is : 0
# For n_clusters = 3 The bouldin_score is : 0 lower Is better
# For n_clusters = 3 The calinski_harabasz_score is : 0 higher Is better



init random weights ... [[1.596113   0.2792312  1.84541319 ... 0.90242312 2.13833932 2.38846663]
 [2.84616178 1.56352273 3.81610094 ... 1.52895426 2.12921307 3.87571337]
 [3.71175832 4.32701986 2.38275872 ... 2.88490481 1.90831913 0.57578808]
 ...
 [1.77112796 4.19133399 2.63460943 ... 4.44256821 4.99078327 4.1809472 ]
 [0.93111652 2.22783037 2.77384989 ... 2.75182714 0.39966984 1.19430342]
 [3.41624856 4.45493861 3.09256895 ... 0.67762882 4.22309324 2.71495288]]
indexData: 998, User_ID: 49841
 Batch Number:  1
(9, 12773)
_sols :  (10, 9, 12773)
_best_solutions :  (1, 2)
_sols :  (10, 9, 12773)
_best_solutions :  (2, 2)
_sols :  (10, 9, 12773)
_best_solutions :  (3, 2)
_sols :  (10, 9, 12773)
_best_solutions :  (4, 2)
_sols :  (10, 9, 12773)
_best_solutions :  (5, 2)
_sols :  (10, 9, 12773)
_best_solutions :  (6, 2)
_sols :  (10, 9, 12773)
_best_solutions :  (7, 2)
_sols :  (10, 9, 12773)
_best_solutions :  (8, 2)
_sols :  (10, 9, 12773)
_best_solutions :  (9, 2)
_sols :  (10, 9, 12773

In [5]:
from os import error
import numpy as np
import pandas as pd
from numpy.core.fromnumeric import shape
from sklearn.metrics import silhouette_score
from sklearn.metrics import davies_bouldin_score
from sklearn.metrics import calinski_harabasz_score
from SOM.SelfOrganisingMaps import SelfOrganisingMaps
from WOA.WhaleClustersOptimization import WhaleClustersOptimization
from Models.Core.ObjGlobalRequest import ObjGlobalRequest
import Models.ObjHotelReviews as ObjHotelReviews
import Repository.HotelReviewsRepository as HotelReviewsRepository
import Repository.UsersRepository as UsersRepository
import Helper.ListHelper as ListHelper
Users = UsersRepository.GetList(ObjGlobalRequest())
User = ObjHotelReviews.ObjHotelReviews_GetList_Request()
User.User_ID = Users.List[0]["User_ID"]
ReviewsRequest0 = ObjGlobalRequest(User)
ReviewsResponse0 = HotelReviewsRepository.GetList(ReviewsRequest0)
Matrix = []
MatrixSize = len(ReviewsResponse0.List)
BatchSize = 1000
Clusters = 11
SOM = SelfOrganisingMaps(Clusters, MatrixSize, 50)
_silhouette_score = 0
_bouldin_score = 0
_calinski_harabasz_score = 0
BatchNumber = 0
index = 0
indexData = 0

for u in Users.List:
    if(index == 0):
        Matrix = np.zeros((BatchSize, MatrixSize), dtype=int)
    User = ObjHotelReviews.ObjHotelReviews_GetList_Request()
    User.User_ID = u["User_ID"]
    ReviewsRequest = ObjGlobalRequest(User)
    ReviewsResponse = HotelReviewsRepository.GetList(ReviewsRequest)
    UsersReviews_DataFrame = pd.DataFrame(ReviewsResponse.List)
    Matrix[index] = UsersReviews_DataFrame["Rate"]
    print(f"indexData: {indexData}, User_ID: {u['User_ID']}" , end="\r")
    index += 1
    indexData += 1
    if (index + 1 == BatchSize):
        BatchNumber += 1
        print("\n Batch Number: ", BatchNumber)
        SOM.Fit(Matrix)
        # print("shape Matrix: ", shape(Matrix))
        # Optimization Cluster Centers  
        print(shape(SOM.Weights))
        woa = WhaleClustersOptimization(SOM.Weights, SOM.Labels, Matrix)
        # print(shape(woa.basePoint))        
        # print(shape(woa._sols))
        for _ in range(10):
            woa.optimize()
        # print(shape(woa._best_solution))
        # print(woa._best_solution)
        SOM.Weights = woa._best_solution
        Unique_Labels = ListHelper.Unique(SOM.Labels)
        if (len(Unique_Labels) == 1):
            if(SOM.Labels[0] == 0):
                SOM.Labels[0] = 1
            else:
                SOM.Labels[0] = 0
        _silhouette_score += silhouette_score(Matrix, SOM.Labels, metric="euclidean")
        _bouldin_score += davies_bouldin_score(Matrix, SOM.Labels)
        _calinski_harabasz_score += calinski_harabasz_score(Matrix, SOM.Labels)
        index = 0

print("For n_clusters =", Clusters, "The silhouette_score is :", _silhouette_score)
print("For n_clusters =", Clusters, "The bouldin_score is :", _bouldin_score, "lower Is better")
print("For n_clusters =", Clusters, "The calinski_harabasz_score is :", _calinski_harabasz_score, "higher Is better")

print("End Of SOM Clustering")
# For n_clusters = 3 The silhouette_score is : 0
# For n_clusters = 3 The bouldin_score is : 0 lower Is better
# For n_clusters = 3 The calinski_harabasz_score is : 0 higher Is better



init random weights ... [[2.42481505 1.26458203 4.40751886 ... 0.60560909 3.61153901 4.71939284]
 [3.92846399 2.41547281 0.40603171 ... 2.29416636 0.20534594 3.3569942 ]
 [4.49745728 1.58897365 4.59820326 ... 2.05227095 4.40124328 1.40123526]
 ...
 [2.33404045 0.25972737 4.86662584 ... 3.51275447 2.24121659 2.97777846]
 [0.26962026 0.78944427 2.69142188 ... 2.12453374 4.60770807 4.68903502]
 [3.25556976 3.12604964 0.60034129 ... 1.08889914 0.57246249 2.24191297]]
indexData: 998, User_ID: 5463
 Batch Number:  1
(11, 12773)
_sols :  (10, 11, 12773)
_best_solutions :  (1, 2)
_sols :  (10, 11, 12773)
_best_solutions :  (2, 2)
_sols :  (10, 11, 12773)
_best_solutions :  (3, 2)
_sols :  (10, 11, 12773)
_best_solutions :  (4, 2)
_sols :  (10, 11, 12773)
_best_solutions :  (5, 2)
_sols :  (10, 11, 12773)
_best_solutions :  (6, 2)
_sols :  (10, 11, 12773)
_best_solutions :  (7, 2)
_sols :  (10, 11, 12773)
_best_solutions :  (8, 2)
_sols :  (10, 11, 12773)
_best_solutions :  (9, 2)
_sols :  (10,

In [6]:
from os import error
import numpy as np
import pandas as pd
from numpy.core.fromnumeric import shape
from sklearn.metrics import silhouette_score
from sklearn.metrics import davies_bouldin_score
from sklearn.metrics import calinski_harabasz_score
from SOM.SelfOrganisingMaps import SelfOrganisingMaps
from WOA.WhaleClustersOptimization import WhaleClustersOptimization
from Models.Core.ObjGlobalRequest import ObjGlobalRequest
import Models.ObjHotelReviews as ObjHotelReviews
import Repository.HotelReviewsRepository as HotelReviewsRepository
import Repository.UsersRepository as UsersRepository
import Helper.ListHelper as ListHelper
Users = UsersRepository.GetList(ObjGlobalRequest())
User = ObjHotelReviews.ObjHotelReviews_GetList_Request()
User.User_ID = Users.List[0]["User_ID"]
ReviewsRequest0 = ObjGlobalRequest(User)
ReviewsResponse0 = HotelReviewsRepository.GetList(ReviewsRequest0)
Matrix = []
MatrixSize = len(ReviewsResponse0.List)
BatchSize = 1000
Clusters = 13
SOM = SelfOrganisingMaps(Clusters, MatrixSize, 50)
_silhouette_score = 0
_bouldin_score = 0
_calinski_harabasz_score = 0
BatchNumber = 0
index = 0
indexData = 0

for u in Users.List:
    if(index == 0):
        Matrix = np.zeros((BatchSize, MatrixSize), dtype=int)
    User = ObjHotelReviews.ObjHotelReviews_GetList_Request()
    User.User_ID = u["User_ID"]
    ReviewsRequest = ObjGlobalRequest(User)
    ReviewsResponse = HotelReviewsRepository.GetList(ReviewsRequest)
    UsersReviews_DataFrame = pd.DataFrame(ReviewsResponse.List)
    Matrix[index] = UsersReviews_DataFrame["Rate"]
    print(f"indexData: {indexData}, User_ID: {u['User_ID']}" , end="\r")
    index += 1
    indexData += 1
    if (index + 1 == BatchSize):
        BatchNumber += 1
        print("\n Batch Number: ", BatchNumber)
        SOM.Fit(Matrix)
        # print("shape Matrix: ", shape(Matrix))
        # Optimization Cluster Centers  
        print(shape(SOM.Weights))
        woa = WhaleClustersOptimization(SOM.Weights, SOM.Labels, Matrix)
        # print(shape(woa.basePoint))        
        # print(shape(woa._sols))
        for _ in range(10):
            woa.optimize()
        # print(shape(woa._best_solution))
        # print(woa._best_solution)
        SOM.Weights = woa._best_solution
        Unique_Labels = ListHelper.Unique(SOM.Labels)
        if (len(Unique_Labels) == 1):
            if(SOM.Labels[0] == 0):
                SOM.Labels[0] = 1
            else:
                SOM.Labels[0] = 0
        _silhouette_score += silhouette_score(Matrix, SOM.Labels, metric="euclidean")
        _bouldin_score += davies_bouldin_score(Matrix, SOM.Labels)
        _calinski_harabasz_score += calinski_harabasz_score(Matrix, SOM.Labels)
        index = 0

print("For n_clusters =", Clusters, "The silhouette_score is :", _silhouette_score)
print("For n_clusters =", Clusters, "The bouldin_score is :", _bouldin_score, "lower Is better")
print("For n_clusters =", Clusters, "The calinski_harabasz_score is :", _calinski_harabasz_score, "higher Is better")

print("End Of SOM Clustering")
# For n_clusters = 3 The silhouette_score is : 0
# For n_clusters = 3 The bouldin_score is : 0 lower Is better
# For n_clusters = 3 The calinski_harabasz_score is : 0 higher Is better



init random weights ... [[2.67649303 2.54574434 0.39247799 ... 2.58637476 2.33652642 3.68480865]
 [2.93248028 4.79237821 2.12283334 ... 3.87420721 3.47621986 4.02270342]
 [4.15339838 2.85488011 2.78406691 ... 2.44538239 2.42882766 3.32295987]
 ...
 [1.16497636 1.0544678  4.52397271 ... 0.10759525 1.58940879 1.15264974]
 [2.71132746 1.19062084 2.6722145  ... 3.72145048 3.18872177 2.59086462]
 [2.12857067 0.97918997 4.01011323 ... 0.4657959  3.87173091 0.45662615]]
indexData: 998, User_ID: 854745
 Batch Number:  1
(13, 12773)
_sols :  (10, 13, 12773)
_best_solutions :  (1, 2)
_sols :  (10, 13, 12773)
_best_solutions :  (2, 2)
_sols :  (10, 13, 12773)
_best_solutions :  (3, 2)
_sols :  (10, 13, 12773)
_best_solutions :  (4, 2)
_sols :  (10, 13, 12773)
_best_solutions :  (5, 2)
_sols :  (10, 13, 12773)
_best_solutions :  (6, 2)
_sols :  (10, 13, 12773)
_best_solutions :  (7, 2)
_sols :  (10, 13, 12773)
_best_solutions :  (8, 2)
_sols :  (10, 13, 12773)
_best_solutions :  (9, 2)
_sols :  (1